AWSTemplateFormatVersion: '2010-09-09'
Description: ALB y ASG - JordyPrada

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

Resources:

  TargetGroupJordyPrada:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: TG-JordyPrada
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30

  ALBJordyPrada:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ALB-JordyPrada
      Scheme: internet-facing
      SecurityGroups:
        - !ImportValue SGAlbId
      Subnets: !Ref SubnetIds

  ListenerALB:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALBJordyPrada
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupJordyPrada

  LaunchTemplateJordyPrada:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: LT-JordyPrada
      LaunchTemplateData:
        ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
        InstanceType: t3.micro
        SecurityGroupIds:
          - !ImportValue SGInstanciaId
        UserData:
          Fn::Base64: |
            #!/bin/bash
            yum install -y httpd
            systemctl start httpd
            echo '<h1>ASG - JordyPrada</h1>' > /var/www/html/index.html

  ASGJordyPrada:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: ASG-JordyPrada
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '2'
      VPCZoneIdentifier: !Ref SubnetIds
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateJordyPrada
        Version: !GetAtt LaunchTemplateJordyPrada.LatestVersionNumber
      TargetGroupARNs:
        - !Ref TargetGroupJordyPrada

  WarmPoolJordyPrada:
    Type: AWS::AutoScaling::WarmPool
    Properties:
      AutoScalingGroupName: !Ref ASGJordyPrada
      MinSize: 1

Outputs:
  ALBDns:
    Value: !GetAtt ALBJordyPrada.DNSName
    Export:
      Name: ALBDns
  ASGName:
    Value: !Ref ASGJordyPrada
    Export:
      Name: ASGName
  LaunchTemplateId:
    Value: !Ref LaunchTemplateJordyPrada
    Export:
      Name: LaunchTemplateId
