AWSTemplateFormatVersion: '2010-09-09'
Description: ALB y ASG - JordyPrada

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

Resources:

  TargetGroup-JordyPrada:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: TG-JordyPrada
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30

  ALB-JordyPrada:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ALB-JordyPrada
      Scheme: internet-facing
      SecurityGroups:
        - !ImportValue SGAlbId
      Subnets: !Ref SubnetIds

  ListenerALB:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB-JordyPrada
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup-JordyPrada

  LaunchTemplate-JordyPrada:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: LT-JordyPrada
      LaunchTemplateData:
        ImageId: ami-00e801948462f718a
        InstanceType: t3.micro
        SecurityGroupIds:
          - !ImportValue SGInstanciaId
        UserData:
          Fn::Base64: |
            #!/bin/bash
            yum install -y httpd
            systemctl start httpd
            echo '<h1>ASG - JordyPrada</h1>' > /var/www/html/index.html

  ASG-JordyPrada:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: ASG-JordyPrada
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '2'
      VPCZoneIdentifier: !Ref SubnetIds
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate-JordyPrada
        Version: !GetAtt LaunchTemplate-JordyPrada.LatestVersionNumber
      TargetGroupARNs:
        - !Ref TargetGroup-JordyPrada

  WarmPool-JordyPrada:
    Type: AWS::AutoScaling::WarmPool
    Properties:
      AutoScalingGroupName: !Ref ASG-JordyPrada
      MinSize: 1

Outputs:
  ALBDns:
    Value: !GetAtt ALB-JordyPrada.DNSName
    Export:
      Name: ALBDns
  ASGName:
    Value: !Ref ASG-JordyPrada
    Export:
      Name: ASGName
  LaunchTemplateId:
    Value: !Ref LaunchTemplate-JordyPrada
    Export:
      Name: LaunchTemplateId
