AWSTemplateFormatVersion: '2010-09-09'
Description: Security Groups - JordyPrada

Resources:

  SGInstancia-JordyPrada:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG para instancia EC2 publica
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  SGAlb-JordyPrada:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG para Application Load Balancer
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

Outputs:
  SGInstanciaId:
    Value: !Ref SGInstancia-JordyPrada
    Export:
      Name: SGInstanciaId
  SGAlbId:
    Value: !Ref SGAlb-JordyPrada
    Export:
      Name: SGAlbId