name: Deploy Infrastructure
on:
  push:
    branches: [master]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Security Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/security.yml \
            --stack-name SecurityGroups-JordyPrada \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy EC2 Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/ec2.yml \
            --stack-name EC2-JordyPrada

      - name: Deploy ALB-ASG Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/alb-asg.yml \
            --stack-name ALB-ASG-JordyPrada \
            --parameter-overrides VpcId=vpc-0551a786fff021d6f SubnetIds=subnet-014686d5696588e49

      - name: Deploy Automation Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/automation.yml \
            --stack-name Automation-JordyPrada
